* Chapter 1
** Classical physics
1. Single-values
2. Continuous
** Quantum
1. Discrete
2. Random, but probabilistic
** Concept
Let object M_X represent one of possible state of a qubit.
then we can model a qubit as a_A*M_A + a_B*M_B + a_C*M_C which looks like a linear combination.
Superposition is modeled by a vector where the linear combination of that vector shows all probable positions of that qubit.
* Chapter 2
** Quantum state
Mathematical object that holds all of the physical properties of the particle.
** Ket
|\phi\rangle = c|A\rangle + ...
|\phi\rangle = \int{}dx*c(x)*|x\rangle continuous set
* Chapter 3
** Hilbert space
Equipped with inner product and is Cauchy complete
Cauchy complete - every convergent series of vectors converges to the vector inside the vector space.
* Chapter 4
** Inner product
\lang{}\psi|\phi\rang = c
flipping inner product should add complex conjugate *
** Kronecker delta
\delta_ij = 1 when i = j
\delta_ij = 0 when i \neq j


* Source
https://www.youtube.com/playlist?list=PL8ER5-vAoiHAWm1UcZsiauUGPlJChgNXC
